# Silenciar logs de Hibernate
org.hibernate.level=OFF
org.hibernate.SQL.level=OFF
org.hibernate.engine.level=OFF
org.hibernate.cache.level=OFF
org.hibernate.resource.level=OFF

# Solo mostrar errores graves
.level=SEVERE
handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level=SEVERE
